<ERROR>
"Core Error. File System Error."
<NOERRORS>
"No Error."
<ERROR_OPEN_FILE>
"Error opening the file."
<ERROR_READ_FILE>
"Error reading the file."
<ERROR_PARSE_MOUNT_FILE_QUOTES>
"Error parsing the mount file. No closing quotes."
<ERROR_PARSE_MOUNT_FILE>
"Error parsing the mount file."
<ERROR_MOUNT_FS>
"Error mounting the file system."
<ERROR_OPEN_FOLDER>
"Couldn't open the directory."
<ERROR_WRITE_FILE>
"Error while writing the file."
<ERROR_INCORRECT_FILE>
"Incorrect file."
<ERROR_INCORRECT_MOUNTPOINT>
"Incorrect mountpoint"
<ERROR_OVERWRITE_DENIED>
"Can't overwrite the file."
<ERROR_LOST_QUOTES>
"Lost quotes."
<ERROR_PARSE_STRING>
"Error parsing the string."
<ERROR_WRONG_BYTEORDER>
"Wrong byteorder. Program can't read files with unknown byteorder."
<ERROR_INCORRECT_PATH>
"Path incorrect or directory or file don't exist."
<ERROR_INCORRECT_CRC32>
"Crc check is failed. File is broken."
<ERROR_FUNCTION_ARGUMENTS>
"Function was called with wrong arguments."
<ERROR_OLD_FSMAN>
"FSMan version is too old or file is from the future."
<ERROR_ADD_FILE>
"Couldn't add the file."
<WARNING>
"Core Warning. File System Warning."
<NOWARNINGS>
"No Warning."
<WARNING_OVERWRITE>
"File was overwritten."
<WARNING_EMPTY_STRING>
"Empty string. Nothing to parse."
<WARNING_WRONG_COMMAND>
"Wrong syntax or unknown command."
<WARNING_INCORRECT_PATH>
"Path incorrect or directory doesn't exist."